apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dny2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dny2
    app.kubernetes.io/part-of: ci1t-830-0087-app
  name: devfile-sample-dny2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dny2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dny2
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0087-tenant/ci1t-830-0087-app/devfile-sample-dny2@sha256:d77f845a78686ba694a09c0ac28e3b451e48d4a1086fcfcef3bd3bcab835f98a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
